apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-monkey
  namespace: testing
  labels:
    app: chaos-monkey
spec:
  selector:
    matchLabels:
      app: chaos-monkey
  template:
    metadata:
      labels:
        app: chaos-monkey
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  
    spec:
  replicas: 1  
  containers:
  - name: chaos-monkey
    image: ChaosMonkey:1.0
    env:
      - name: DELETE_BY_LABEL
        value: "false"
      - name: LABEL_TO_DELETE
        value: "null"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
