apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: testing
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  
  minReplicas: 2
  maxReplicas: 4
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        ports:
        - containerPort: 8443
          protocol: TCP
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /index.html
            port: 8443
          initialDelaySeconds: 10
          periodSeconds: 5
